Details Popup window
wajahatalli/Portfolio pull request #12
Opened 2022-11-18 05:47 UTC by wajahatalli

Added a modal using javascript.
Created an object to store content to be fed to the main page.

2022-11-18 06:10 UTC, tufoinnkuo10 requested changes
Hi @wajahatalli 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally

Required Changes ♻️
Check the comments under the review

![tufoin](https://media.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif)

Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-11-18 06:10 UTC, tufoinnkuo10 commented on index.js
> +    image: '../images/work-img2.png',
- [ ] kindly ensure that in the mobile version,  the text is aligned with the image and technologies like in the figma version
![Screenshot (593)_LI](https://user-images.githubusercontent.com/65298048/202631918-cd2070aa-e671-453a-834b-2d2ad99ff312.jpg)

2022-11-18 06:10 UTC, tufoinnkuo10 commented on index.js
> +    description:
- [ ] please centralize your image in the desktop popup , align it with the text and see source button like in the figma design. great work.
yours
![Screenshot (594)_LI](https://user-images.githubusercontent.com/65298048/202632743-d0f9a2ae-a497-4151-a40a-e530764bbfc6.jpg)
figma
![Screenshot (595)](https://user-images.githubusercontent.com/65298048/202633003-c6bfaeab-96b4-4ebe-8165-28b605f9b568.png)

2022-11-19 09:21 UTC, wajahatalli commented
- Fixed eslinter error
- Fixed image position
- Fixed text position in the mobile version
- Made all required changes
- Its perfect now

2022-11-19 09:32 UTC, PinkMoon25 approved these changes
Hi @wajahatalli , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
 You used the correct Github flow :heavy_check_mark: 
 Descriptive pull request message :heavy_check_mark: 
 linter error checks validated :heavy_check_mark: 
Documented your work professionally :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-19 09:36 UTC, merged